name: "Richard's"
favicon: null
layout_spectrum: 1
typography_spectrum: 0.0611
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e5c965'
    - '#eff3fe'
    - '#1c1e12'
    - '#988e85'
    - '#994900'
  brandStrength: 0.0625
  lightness: 0.5393065817188472
  saturation: 0.5
  rhythmicContrast: 0.5313291321508586
purpose: []
